name: weather_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.8
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
